_target_: aimat.models.ResNet
block_type: 'BasicBlock'  # or 'Bottleneck'
layers: [3, 4, 6, 3]     # layers in each block, for ResNet50: [3, 4, 6, 3], for ResNet101: [3, 4, 23, 3], for ResNet152: [3, 8, 36, 3]
num_classes: 1000        # number of output classes
input_size:
  width: 224
  height: 224
  channels: 3
